In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

In [2]:
W = np.array([0,2,-1,2,0,-1,-1,-1,1]).reshape(3,3)
b = np.array([0.5,0.5,.5]).reshape(3,1)

In [3]:
def energy (x):
    energy = -(x.T@W@x + 2*b.T @x)
    return energy

In [4]:
x = np.array([1,1,-1]).reshape(3,1)

In [5]:
np.sign(W@x + b)

array([[ 1.],
       [ 1.],
       [-1.]])

In [6]:
energy(x)

array([[-10.]])

In [7]:
x = np.array([1,-1,1]).reshape(3,1)
np.sign(W@x + b)

array([[-1.],
       [ 1.],
       [ 1.]])

In [8]:
energy(x)

array([[ 2.]])

In [9]:
x = np.array([-1,1,1]).reshape(3,1)
np.sign(W@x + b)

array([[ 1.],
       [-1.],
       [ 1.]])

In [10]:
energy(x)

array([[ 2.]])

In [11]:
x = np.array([1,1,1]).reshape(3,1)
np.sign(W@x + b)

array([[ 1.],
       [ 1.],
       [-1.]])

In [12]:
energy(x)

array([[-4.]])

In [32]:
x = np.array([1,-1,-1]).reshape(3,1)
np.sign(W@x + b)

array([[-1.],
       [ 1.],
       [-1.]])

In [33]:
energy(x)

array([[ 4.]])

In [34]:
x = np.array([-1,1,-1]).reshape(3,1)
np.sign(W@x + b)

array([[ 1.],
       [-1.],
       [-1.]])

In [35]:
energy(x)

array([[ 4.]])

In [36]:
x = np.array([-1,-1,1]).reshape(3,1)
np.sign(W@x + b)

array([[-1.],
       [-1.],
       [ 1.]])

In [37]:
energy(x)

array([[-8.]])

In [13]:
x = np.array([-1,-1,-1]).reshape(3,1)
np.sign(W@x + b)

array([[-1.],
       [-1.],
       [ 1.]])

In [14]:
energy(x)

array([[ 2.]])